XJSFUI/src/main/java/org/cps/prov/model/Application.java
package org.cps.prov.model;

import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.cps.identity.model.User;

 
/**
 * Entity bean with JPA annotations Hibernate provides JPA implementation
 *
 */
@Entity
@Table(name = "APPLICATION")
@ManagedBean(name = "application")
public class Application {
	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	@Column(unique=true,nullable=false)
	private String name;

	private String description;
	
	@Column(columnDefinition="tinyint(1) default 1")
	private boolean isTrusted;

	@ManyToOne(cascade=CascadeType.MERGE,fetch = FetchType.EAGER)
	@JoinColumn(name="app_def_id")
	private ApplicationDefinition appDefinition;
	
	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn(name="app_id")
	private List<ApplicationParams> params;

    @ManyToMany(mappedBy="applications")
    private Collection<ProvisioningPolicy> provPolicies;

	
    private String createdBy;
    private String updatedBy;
    private Date createdDate;
    private Date updatedDate;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public ApplicationDefinition getAppDefinition() {
		return appDefinition;
	}

	public void setAppDefinition(ApplicationDefinition appDefinition) {
		this.appDefinition = appDefinition;
	}

	
	public List<ApplicationParams> getParams() {
		return params;
	}

	public void setParams(List<ApplicationParams> params) {
		this.params = params;
	}

	public boolean isTrusted() {
		return isTrusted;
	}

	public void setTrusted(boolean isTrusted) {
		this.isTrusted = isTrusted;
	}

	
	
 	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	
	
	public Collection<ProvisioningPolicy> getProvPolicies() {
		return provPolicies;
	}

	public void setProvPolicies(Collection<ProvisioningPolicy> provPolicies) {
		this.provPolicies = provPolicies;
	}

	@Override
	public String toString() {
		return "id=" + id + ", name=" + name + ", description=" + description + ", addDefinition : " + appDefinition.getName();
	}

}

XJSFUI/src/main/java/org/cps/web/ui/beans/UserAttributesBean.java
package org.cps.web.ui.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.model.SelectItem;

import org.primefaces.PrimeFaces;
import org.primefaces.context.RequestContext;
import org.cps.web.client.IdentityClientService;
import org.idx.identity.dob.USER_ATTR_TYPE;
import org.idx.identity.dob.UserAttributeDOB;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import lombok.Data;

@Data
@Component
@Scope("session")
public class UserAttributesBean implements Serializable {
	
	@Autowired
	private IdentityClientService identityService;
	
	private List<UserAttributeDOB> userAttributes;
	
	private UserAttributeDOB userAttr = new UserAttributeDOB();

	private List<SelectItem> userAttrTypes;
	
	
	
	@PostConstruct
	public void init() {
		System.out.println("######### init UserAttributesBean #########");	
		userAttributes = identityService.getUserAttributes();
		
		userAttrTypes = new ArrayList<SelectItem>();
		
		SelectItem userAttrType1 = new SelectItem();
		
		userAttrType1.setLabel("String");
		userAttrType1.setValue(USER_ATTR_TYPE.STRING);
		
		userAttrTypes.add(userAttrType1);

		SelectItem userAttrType2 = new SelectItem();

		userAttrType2.setLabel("String");
		userAttrType2.setValue(USER_ATTR_TYPE.SECRET);
		
		userAttrTypes.add(userAttrType2);

		SelectItem userAttrType3 = new SelectItem();

		userAttrType3.setLabel("Date");
		userAttrType3.setValue(USER_ATTR_TYPE.DATE);
		
		userAttrTypes.add(userAttrType3);

		SelectItem userAttrType4 = new SelectItem();

		userAttrType4.setLabel("Boolean");
		userAttrType4.setValue(USER_ATTR_TYPE.BOOLEAN);
		
		userAttrTypes.add(userAttrType4);

		SelectItem userAttrType5 = new SelectItem();

		userAttrType5.setLabel("Number");
		userAttrType5.setValue(USER_ATTR_TYPE.NUMBER);
		
		userAttrTypes.add(userAttrType5);

	}
	
	
	
	
	public void openCreateAttribute(){
		System.out.println("######### openCreateAttribute UserAttributesBean #########");	

		Map<String,Object> options = new HashMap<String, Object>();
		options.put("resizable", false);
        options.put("draggable", false);
        options.put("modal", true);
		PrimeFaces.current().dialog().openDynamic("createUserAttribute", options, null);
		
		
//		RequestContext context2 = RequestContext.getCurrentInstance();
//		  context2.execute("PF('createUserAttribute').show()");

	}
	
	public void createUserAttributes(){
		
	}
	
}

XJSFUI/src/main/webapp/pages/admin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      >
    <h:body>
 
    	<ui:composition template="../common/adminLayout.xhtml">
     		<ui:define name="west">
    			<ui:include src="adminLeftPane.xhtml" />
    		</ui:define>
     		<ui:define name="center">
    			<ui:include src="adminCenterPane.xhtml" />
    		</ui:define>
    		<ui:define name="north">
    			<ui:include src="../common/adminHeader.xhtml" />
    		</ui:define>
    		
    	</ui:composition>
    	
    	
    	
 
    </h:body>
 
</html>

XJSFUI/src/main/webapp/pages/createApplication.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:hys="http://java.sun.com/jsf/composite/hys">

<h:body>

	<ui:composition>
		<h:form id="ApplicationForm">

			<p:growl id="growl" sticky="true" showDetail="true" />

			<p:wizard widgetVar="AppWizard" flowListener="#{applicationWizardBean.onFlowProcess}">
				<p:tab id="basicInfo" title="Application">
					<p:panel header="Application Details">
						<p:messages />
						<h:panelGrid columns="2" columnClasses="label, value">
							<h:outputText value="Application Name: *" />
							<p:inputText value="#{applicationWizardBean.application.name}"
								required="true" label="Application Name" />

							<h:outputText value="Display Name: *" />
							<p:inputText
								value="#{applicationWizardBean.application.displayName}"
								required="true" label="Display Name" />

							<h:outputText value="Description: " />
							<p:inputTextarea rows="6" cols="33" autoResize="false"
								value="#{applicationWizardBean.application.description}" />

							<p:outputLabel for="appType" value="Application Type: " />
							<p:selectOneMenu id="appType" required="true"
								value="#{applicationWizardBean.application.configuratorType}">
								<f:selectItem itemLabel="Select One" itemValue="" />
								<f:selectItems value="#{applicationWizardBean.appTypes}" />
							</p:selectOneMenu>
							<p:outputLabel for="@next" value="Trusted : " />
							<p:selectBooleanCheckbox
								value="#{applicationWizardBean.application.trusted}" />

						</h:panelGrid>
					</p:panel>
				</p:tab>

				<p:tab id="configurator" title="Configuration">
					<p:panel header="Application Configuration">
						<p:messages />
						
 						
						<h:panelGrid columns="2" columnClasses="label, value">
 
							<p:repeat
								value="#{applicationWizardBean.selectedApplicationType.appTypeParams}"
								var="param1">
								<h:panelGrid columns="2" columnClasses="label, value">

									<h:outputText value="#{param1.label} : " />
									<p:inputText value="#{param1.value}" size="40"
										readonly="#{!param1.editable}" disabled="#{!param1.editable}">
																		<p:ajax event="blur"
									listener="${applicationWizardBean.updateValue()}" />
										</p:inputText>

								</h:panelGrid>
							</p:repeat>
						</h:panelGrid>

					</p:panel>
				</p:tab>

				<p:tab id="profile" title="Profile">
					<p:panel header="Profile Definition">
						<p:messages />
						<h:panelGrid columns="2" columnClasses="label, value">
							<h:outputText value="Profile Name: *" />
							<p:inputText
								value="#{applicationWizardBean.application.profile.name}"
								required="true" label="Profile Name" />
						</h:panelGrid>

						<h:panelGrid columns="2" columnClasses="label, value">

						</h:panelGrid>

						<h:panelGrid columns="4" columnClasses="label, value">
							<h:outputText value="Add Attribute" size="40" />
							<p:commandButton id="withIcon" icon="add"
								actionListener="${applicationWizardBean.addProfileAttributeRow()}"
								process="@this"
								update="adminTabPanelView:adminTabPanel:ApplicationForm:profileAttr2" />
							<h:outputText value="&#160;" />
							<h:outputText value="&#160;" />
						</h:panelGrid>


						<p:dataTable id="profileAttr2" widgetVar="profileAttr2"
							var="profileAttr" value="#{applicationWizardBean.profileAttrs}"
							editable="true" style="margin-bottom:20px">

							<p:column headerText="IDX Attribute">
								<p:inputText id="pName" value="#{profileAttr.name}"
									style="width:100%">
									<p:ajax event="blur"
										listener="${applicationWizardBean.updateProfileAttributeIDXName(profileAttrs)}" />
								</p:inputText>
							</p:column>

							<p:column headerText="Target Attribute">
								<p:inputText value="#{profileAttr.targetAttrName}"
									style="width:100%">
									<p:ajax event="blur"
										listener="${applicationWizardBean.updateProfileAttributeTargetName(profileAttrs)}" />
								</p:inputText>
							</p:column>

							<p:column width="40">
								<p:commandLink id="ajax"
									update="adminTabPanelView:adminTabPanel:ApplicationForm:profileAttr2"
									process="@this"
									actionListener="#{applicationWizardBean.removeProfileAttributeRow(profileAttr)}">
									<h:outputText value="Remove" />
								</p:commandLink>
							</p:column>

						</p:dataTable>

					</p:panel>
				</p:tab>

				<p:tab id="rule" title="Rule">
					<p:panel header="Matching Rule">
						<p:messages />
						<h:panelGrid columns="2" columnClasses="label, value">

							<p:outputLabel for="idxAttribute" value="IDX Attribute:" />
							<p:selectOneMenu id="idxAttribute"
								value="#{applicationWizardBean.matchingRule.idxAttribute}"
								style="width:125px">
								<f:selectItem itemLabel="Select One" itemValue="" />

								<f:selectItems value="#{applicationWizardBean.idxAttributes}" />
								<p:ajax event="blur"
									listener="${applicationWizardBean.updateValue()}" />

							</p:selectOneMenu>


							<p:outputLabel for="condition" value="Condition:" />
							<p:selectOneMenu id="condition"
								value="#{applicationWizardBean.matchingRule.matchingCondition}"
								style="width:125px">
								<f:selectItem itemLabel="Select One" itemValue="" />

								<f:selectItems
									value="#{applicationWizardBean.matchingCondition}" />
								<p:ajax event="blur"
									listener="${applicationWizardBean.updateValue()}" />

							</p:selectOneMenu>

							<p:outputLabel for="targetAttribute" value="Target Attribute:" />
							<p:selectOneMenu id="targetAttribute"
								value="#{applicationWizardBean.matchingRule.tgtAttribute}"
								style="width:125px">
								<f:selectItem itemLabel="Select One" itemValue="" />

								<f:selectItems value="#{applicationWizardBean.targetAttributes}" />
								<p:ajax event="blur"
									listener="${applicationWizardBean.updateValue()}" />

							</p:selectOneMenu>

						</h:panelGrid>

					</p:panel>
					<p:panel header="Action Rule">
						<p:messages />

						<h:panelGrid columns="3" columnClasses="label, value">

							<h:outputText value="Add Action" size="40" />
							<p:commandButton id="addMatchingAction" icon="add"
								actionListener="${applicationWizardBean.addMatchingActionRow()}"
								process="@this" update="@form" />
							<h:outputText value="&#160;" />


							<p:dataTable id="matchingAction" widgetVar="matchingAction"
								var="matchingAction"
								value="#{applicationWizardBean.matchingActions}" editable="true"
								style="margin-bottom:20px">

								<p:column headerText="Condition">


									<p:selectOneMenu id="mathcingActCondition"
										value="#{matchingAction.aggCondition}" style="width:125px">
										<f:selectItem itemLabel="Select One" itemValue="" />

										<f:selectItems
											value="#{applicationWizardBean.matchingActionCondition}" />
										<p:ajax event="blur"
											listener="${applicationWizardBean.updateValue()}" />

									</p:selectOneMenu>


								</p:column>

								<p:column headerText="Action">

									<p:selectOneMenu id="mathcingActAction"
										value="#{matchingAction.aggAction}" style="width:125px">
										<f:selectItem itemLabel="Select One" itemValue="" />

										<f:selectItems
											value="#{applicationWizardBean.matchingActionList}" />
										<p:ajax event="blur"
											listener="${applicationWizardBean.updateValue()}" />

									</p:selectOneMenu>

								</p:column>

								<p:column width="40">
									<p:commandLink id="ajax" update="@form" process="@this"
										actionListener="#{applicationWizardBean.removeMatchingActionRow(matchingAction)}">
										<h:outputText value="Remove" />
									</p:commandLink>
								</p:column>

							</p:dataTable>



						</h:panelGrid>

					</p:panel>
				</p:tab>


				<p:tab id="confirm" title="Confirmation">
					<p:panel header="Confirmation">

						<p:fieldset legend="Application" style="margin-bottom:20px">

							<h:panelGrid columns="2" columnClasses="label, value">

								<h:outputText value="Name: " />
								<h:outputText value="#{applicationWizardBean.application.name}"
									styleClass="outputLabel" />

								<h:outputText value="Display Name: " />
								<h:outputText
									value="#{applicationWizardBean.application.displayName}"
									styleClass="outputLabel" />

								<h:outputText value="Description: " />
								<h:outputText
									value="#{applicationWizardBean.application.description}"
									styleClass="outputLabel" />

								<h:outputText value="Trusted: " />
								<h:outputText
									value="#{applicationWizardBean.application.trusted}"
									styleClass="outputLabel" />

							</h:panelGrid>
							
							<p:commandLink id="ajax1" oncomplete="PF('AppWizard').loadStep('basicInfo', false)">
								<h:outputText value="Edit" />
							</p:commandLink>
							

						</p:fieldset>


						<p:fieldset legend="Configuration" style="margin-bottom:20px">

							<h:panelGrid columns="2" columnClasses="label, value">
							
							
															<p:dataTable widgetVar="profileAttr21" var="configParam"
									value="#{applicationWizardBean.selectedApplicationType.appTypeParams}" editable="true"
									style="margin-bottom:20px">

									<p:column headerText="Name">
										<p:outputLabel id="cName" value="#{configParam.label}"
											style="width:100%" />
									</p:column>
									<p:column headerText="Value">
										<p:outputLabel id="cValue" value="#{configParam.value}"
											style="width:100%" />
									</p:column>
							</p:dataTable>

							</h:panelGrid>
							<p:commandLink id="ajax2" oncomplete="PF('AppWizard').loadStep('configurator', false)">
								<h:outputText value="Edit" />
							</p:commandLink>

						</p:fieldset>

						<p:fieldset legend="Profile" style="margin-bottom:20px">

							<h:panelGrid columns="2" columnClasses="label, value">
								<h:outputText value="Profile Name: *" />
								<h:outputText
									value="#{applicationWizardBean.application.profile.name}" />
							</h:panelGrid>


							<h:panelGrid>


								<p:dataTable widgetVar="profileAttr21" var="profileAttr1"
									value="#{applicationWizardBean.profileAttrs}" editable="true"
									style="margin-bottom:20px">

									<p:column headerText="IDX Attribute">
										<p:outputLabel id="pName" value="#{profileAttr1.name}"
											style="width:100%" />
									</p:column>

									<p:column headerText="Target Attribute">
										<p:outputLabel value="#{profileAttr1.targetAttrName}"
											style="width:100%" />
									</p:column>



								</p:dataTable>

							</h:panelGrid>

<p:commandLink id="ajax3" oncomplete="PF('AppWizard').loadStep('profile', false)">
								<h:outputText value="Edit" />
							</p:commandLink>
							

						</p:fieldset>

						<p:fieldset legend="Rule" style="margin-bottom:20px">


							<p:panel header="Matching Rule">
								<p:messages />
								<h:panelGrid columns="2" columnClasses="label, value">

									<p:outputLabel value="IDX Attribute:" />
									<p:outputLabel value="#{applicationWizardBean.matchingRule.idxAttribute}" />

									<p:outputLabel value="Condition:" />
									<p:outputLabel value="#{applicationWizardBean.matchingRule.matchingCondition}" />

									<p:outputLabel value="Target Attribute:" />
									<p:outputLabel value="#{applicationWizardBean.matchingRule.tgtAttribute}" />

								</h:panelGrid>

							</p:panel>
							<p:panel header="Action Rule">
								<p:messages />

								<h:panelGrid columns="3" columnClasses="label, value">

									<p:dataTable id="matchingAction1" widgetVar="matchingAction"
										var="matchingAction"
										value="#{applicationWizardBean.matchingActions}"
										editable="true" style="margin-bottom:20px">

										<p:column headerText="Condition">

									<p:outputLabel value="#{matchingAction.aggCondition}" />

										</p:column>

										<p:column headerText="Action">

									<p:outputLabel value="#{matchingAction.aggAction}" />


										</p:column>

									</p:dataTable>



								</h:panelGrid>

							</p:panel>


							<p:commandLink id="ajax4" oncomplete="PF('AppWizard').loadStep('rule', false)">
								<h:outputText value="Edit" />
							</p:commandLink>







						</p:fieldset>



						<p:commandButton value="Submit"
							actionListener="#{applicationWizardBean.save}" update="growl"
							process="@this" />
					</p:panel>
				</p:tab>
			</p:wizard>

		</h:form>

	</ui:composition>

</h:body>

</html>

XJSFUI/src/main/webapp/pages/createEmailTemplate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:hys="http://java.sun.com/jsf/composite/hys">

<h:body>

	<ui:composition>
		<h:form id="EmailTemplateForm">
			<p:messages id="messages" showDetail="true" autoUpdate="true"
				closable="true" />

				<h:panelGrid columns="2" columnClasses="label, value">
					<h:outputText value="Name: *" />
					<p:inputText value="" required="true" label="Application Name" />

					<h:outputText value="Language: *" />
					
					<p:selectOneMenu value="" style="width:125px">
						<f:selectItem itemLabel="English (US)" itemValue="en_us" />
						<f:selectItem itemLabel="English" itemValue="en" />
						<f:selectItem itemLabel="French" itemValue="fr" />
					</p:selectOneMenu>

					<h:outputText value="Encoding: *" />
					<p:inputText value="" required="true" label="" />

  				</h:panelGrid>
  				<h:panelGrid>
 
					<h:outputText value="&#160;" />

 				 <p:textEditor widgetVar="editor2" value="" height="300" style="margin-bottom:10px" placeholder="Enter your content">
				</p:textEditor>
 				</h:panelGrid>
 				
 				    <p:commandButton value="Submit" icon="ui-icon-disk" />
				    <p:commandButton value="Clear" type="button"  icon="ui-icon-close" />
 				
		</h:form>

	</ui:composition>

</h:body>

</html>

XJSFUI/src/main/webapp/pages/createOrg.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:hys="http://java.sun.com/jsf/composite/hys">

<h:body>

	<ui:composition>
		<h:form id="UserForm">

			<p:messages id="messages" showDetail="true" autoUpdate="true"
				closable="true" />

			<p:panelGrid columns="1" cellpadding="10"
				>

				<f:facet name="header">  
        			Create User
				</f:facet>

				<p:fieldset legend="Basic Information" style="margin-bottom:20px">

					<h:panelGrid columns="4" cellpadding="5">


						<p:outputLabel for="firstName" value="First Name " />
						<p:inputText id="firstName" required="true" value="#{userVO.firstName}">
							<f:validateLength minimum="2" />
						</p:inputText>
						<h:outputText value="Middle Name " />
						<p:inputText value="#{userVO.middleName}" />
						<p:outputLabel for="lastName" value="Last Name " />
						<p:inputText id="lastName" required="true" value="#{userVO.lastName}">
						<f:validateLength minimum="2" />
						</p:inputText>

						<p:outputLabel for="displayName" value="Display Name " />
						<p:inputText id="displayName" required="true" value="#{userVO.displayName}" />

						<p:outputLabel for="userType" value="User Type" />
						<p:selectOneMenu id="userType" required="true" value="userVO.userType"
							style="width:125px">
							<f:selectItem itemLabel="Select User Type" itemValue="" />
							<f:selectItem itemLabel="Employee" itemValue="Employee" />
							<f:selectItem itemLabel="Contractor" itemValue="Contractor" />
							<f:selectItem itemLabel="Temp Worker" itemValue="Temp Worker" />
						</p:selectOneMenu>

						<p:outputLabel for="org" value="Organization" />
 						<p:selectOneMenu id="org" required="true" value="userVO.org_key" style="width:125px">
							<f:selectItem itemLabel="Select Organization" itemValue="" />
							<f:selectItem itemLabel="Base" itemValue="Base" />
						</p:selectOneMenu>

						<h:outputText value="Email" />
						<p:inputText value="#{userVO.email}" />

					</h:panelGrid>
				</p:fieldset>

				<p:fieldset legend="Account Information" style="margin-bottom:20px">
				
									<h:panelGrid columns="4" cellpadding="5">
				
					<h:outputText value="User Name " />
					<p:inputText value="#{userVO.userName}" />
					
									<h:inputHidden></h:inputHidden>
									<h:inputHidden></h:inputHidden>
					
					
					<h:outputText value="Password " />
					<p:password id="Password" value="#{userVO.password}" />

					<h:outputText value="Confirm Password " />
					<p:password id="ConfirmPassword" value="#{userVO.password}"/>

					<h:outputText value="Start Date " />
					<p:calendar id="startDate" value="#{userVO.startDate}"
						showOn="button" />

					<h:outputText value="End Date " />
					<p:calendar id="endDate" value="#{userVO.endDate}"
						showOn="button" />
						
						</h:panelGrid>

				</p:fieldset>

				<p:fieldset legend="Contact Information" style="margin-bottom:20px">
				
									<h:panelGrid columns="4" cellpadding="5">
				
					<h:outputText value="Phone Number " />
					<p:inputText value="#{userVO.phoneNumber}" />
					
					<h:outputText value="Mobile Number " />
					
					
					<p:inputText value="#{userVO.mobileNumber}" />
					
														 
					
					
					<h:outputText value="Postal Address 1" />
					
					
					<p:inputText value="#{userVO.postalAddress1}" colspan="2"/>
					
					
					
					

					<h:outputText value="Postal Address 2" />

					<p:inputText value="#{userVO.postalAddress2}"/>

 					


					<h:outputText value="Postal Code" />
					
					
					<p:inputText value="#{userVO.postalCode}" />

					<h:outputText value="City" />

					<p:inputText value="#{userVO.city}" />

					<h:outputText value="State" />
					
					<p:inputText value="#{userVO.state}" />

					<h:outputText value="Country" />
					<p:inputText value="#{userVO.country}" />
						</h:panelGrid>

				</p:fieldset>



				<f:facet name="footer">
					<p:commandButton value="Submit" ajax="true"
						action="#{userBean.createUser(userVO)}">
					</p:commandButton>
					<p:commandButton value="Clear" ajax="false" />
				</f:facet>
			</p:panelGrid>
		</h:form>

	</ui:composition>

</h:body>

</html>

XJSFUI/src/main/webapp/pages/jobDetail.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:hys="http://java.sun.com/jsf/composite/hys">

<h:body>

	<ui:composition>
		<h:form id="jobDetailForm">

			<p:messages id="messages" showDetail="true" autoUpdate="true"
				closable="true" />

  		</h:form>

	</ui:composition>

</h:body>

</html>